In [1]:
import pandas as pd

from src.config import (
    DADOS_2005_2014,
    DADOS_2015_2019,
    DADOS_2020,
    DADOS_2021,
    DADOS_2022,
    DADOS_2023,
    DADOS_2024,
    DADOS_2025,
    DADOS_CONSOLIDADOS,
    DADOS_TRATADOS
)

In [2]:
df_2005_2014 = pd.read_csv(DADOS_2005_2014)
df_2015_2019 = pd.read_csv(DADOS_2015_2019)
df_2020 = pd.read_csv(DADOS_2020)
df_2021 = pd.read_csv(DADOS_2021)
df_2022 = pd.read_csv(DADOS_2022)
df_2023 = pd.read_csv(DADOS_2023, encoding='latin')
df_2024 = pd.read_csv(DADOS_2024, encoding='latin')
df_2025 = pd.read_csv(DADOS_2025, encoding='latin')

In [3]:
df_2005_2014.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2005,Acura,1.7EL,Compact,1.7,4,A4,X,9.2,7.2,8.3,34,191,NaN,NaN
1,2005,Acura,1.7EL,Compact,1.7,4,M5,X,9.1,7.3,8.3,34,191,NaN,NaN
2,2005,Acura,MDX AWD,Sport utility vehicle,3.5,6,A5,Z,15.9,11.1,13.7,21,315,NaN,NaN
3,2005,Acura,NSX,Two-seater,3.0,6,AS4,Z,15.1,10.5,13.0,22,299,NaN,NaN
4,2005,Acura,NSX,Two-seater,3.2,6,M6,Z,15.1,10.5,13.0,22,299,NaN,NaN

In [4]:
df_2015_2019.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2015,Acura,ILX,Compact,2.0,4,AS5,Z,9.7,6.7,8.3,34,191,NaN,NaN
1,2015,Acura,ILX,Compact,2.4,4,M6,Z,10.8,7.4,9.3,30,214,NaN,NaN
2,2015,Acura,ILX Hybrid,Compact,1.5,4,AV7,Z,6.0,6.1,6.1,46,140,NaN,NaN
3,2015,Acura,MDX SH-AWD,Sport utility vehicle: Small,3.5,6,AS6,Z,12.7,9.1,11.1,25,255,NaN,NaN
4,2015,Acura,RDX AWD,Sport utility vehicle: Small,3.5,6,AS6,Z,12.1,8.7,10.6,27,244,NaN,NaN

In [5]:
df_2020.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2020,Acura,ILX,Compact,2.4,4,AM8,Z,9.9,7.0,8.6,33,199,6,3
1,2020,Acura,MDX SH-AWD,Sport utility vehicle: Small,3.5,6,AS9,Z,12.3,9.2,10.9,26,254,4,3
2,2020,Acura,MDX SH-AWD A-SPEC,Sport utility vehicle: Small,3.5,6,AS9,Z,12.2,9.5,11.0,26,258,4,3
3,2020,Acura,MDX Hybrid AWD,Sport utility vehicle: Small,3.0,6,AM7,Z,9.1,9.0,9.0,31,210,5,3
4,2020,Acura,NSX,Two-seater,3.5,6,AM9,Z,11.1,10.8,11.0,26,261,4,3

In [6]:
df_2021.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2021,Acura,ILX,Compact,2.4,4,AM8,Z,9.9,7.0,8.6,33,199,6,3
1,2021,Acura,NSX,Two-seater,3.5,6,AM9,Z,11.1,10.8,11.0,26,256,4,3
2,2021,Acura,RDX SH-AWD,Sport utility vehicle: Small,2.0,4,AS10,Z,11.0,8.6,9.9,29,232,5,6
3,2021,Acura,RDX SH-AWD A-SPEC,Sport utility vehicle: Small,2.0,4,AS10,Z,11.3,9.1,10.3,27,242,5,6
4,2021,Acura,TLX SH-AWD,Compact,2.0,4,AS10,Z,11.2,8.0,9.8,29,230,5,7

In [7]:
df_2022.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2022,Acura,ILX,Compact,2.4,4,AM8,Z,9.9,7.0,8.6,33,200,6,3
1,2022,Acura,MDX SH-AWD,Sport utility vehicle: Small,3.5,6,AS10,Z,12.6,9.4,11.2,25,263,4,5
2,2022,Acura,MDX Type S,Sport utility vehicle: Standard,3.0,6,AS10,Z,13.8,11.2,12.4,23,291,4,5
3,2022,Acura,NSX,Two-seater,3.5,6,AM9,Z,11.1,10.8,11.0,26,256,5,3
4,2022,Acura,RDX SH-AWD,Sport utility vehicle: Small,2.0,4,AS10,Z,11.0,8.6,9.9,29,232,5,6

In [8]:
df_2023.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2023,Acura,Integra,Full-size,1.5,4,AV7,Z,7.9,6.3,7.2,39,167,6,7
1,2023,Acura,Integra A-SPEC,Full-size,1.5,4,AV7,Z,8.1,6.5,7.4,38,172,6,7
2,2023,Acura,Integra A-SPEC,Full-size,1.5,4,M6,Z,8.9,6.5,7.8,36,181,6,6
3,2023,Acura,MDX SH-AWD,Sport utility vehicle: Small,3.5,6,AS10,Z,12.6,9.4,11.2,25,263,4,5
4,2023,Acura,MDX SH-AWD Type S,Sport utility vehicle: Standard,3.0,6,AS10,Z,13.8,11.2,12.4,23,291,4,5

In [9]:
df_2024.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2024,Acura,Integra A-SPEC,Full-size,1.5,4,AV7,Z,8.1,6.5,7.4,38,172,6,7
1,2024,Acura,Integra A-SPEC,Full-size,1.5,4,M6,Z,8.9,6.5,7.8,36,181,6,6
2,2024,Acura,Integra Type S,Full-size,2.0,4,M6,Z,11.1,8.3,9.9,29,230,5,6
3,2024,Acura,MDX SH-AWD,Sport utility vehicle: Small,3.5,6,AS10,Z,12.6,9.4,11.2,25,263,4,5
4,2024,Acura,MDX SH-AWD Type S,Sport utility vehicle: Standard,3.0,6,AS10,Z,13.8,11.2,12.4,23,291,4,5

In [10]:
df_2025.head()

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2025,Acura,ADX AWD,Station wagon: Small,1.5,4,AV7,Z,9.1,7.7,8.5,33,199,6,5
1,2025,Acura,Integra A-SPEC,Full-size,1.5,4,AV7,Z,8.1,6.5,7.4,38,172,6,6
2,2025,Acura,Integra A-SPEC,Full-size,1.5,4,M6,Z,8.9,6.5,7.8,36,181,6,5
3,2025,Acura,Integra Type S,Full-size,2.0,4,M6,Z,11.1,8.3,9.9,29,230,5,5
4,2025,Acura,MDX SH-AWD,Sport utility vehicle: Small,3.5,6,AS10,Z,12.6,9.4,11.2,25,263,4,4

In [11]:
df= pd.concat(
    [df_2005_2014, df_2015_2019, df_2020, df_2021, df_2022, df_2023, df_2024, df_2025 ]
)

df = df.reset_index(drop=True)

df

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
0,2005,Acura,1.7EL,Compact,1.7,4,A4,X,9.2,7.2,8.3,34,191,NaN,NaN
1,2005,Acura,1.7EL,Compact,1.7,4,M5,X,9.1,7.3,8.3,34,191,NaN,NaN
2,2005,Acura,MDX AWD,Sport utility vehicle,3.5,6,A5,Z,15.9,11.1,13.7,21,315,NaN,NaN
3,2005,Acura,NSX,Two-seater,3.0,6,AS4,Z,15.1,10.5,13.0,22,299,NaN,NaN
4,2005,Acura,NSX,Two-seater,3.2,6,M6,Z,15.1,10.5,13.0,22,299,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21209,2025,Volvo,V60 CC B5 AWD,Station wagon: Small,2.0,4,AS8,Z,9.7,7.5,8.7,32,205,5.0,4.0
21210,2025,Volvo,V90 CC B6 AWD,Station wagon: Mid-size,2.0,4,AS8,Z,10.7,8.1,9.5,30,223,5.0,6.0
21211,2025,Volvo,XC40 B5 AWD,Sport utility vehicle: Small,2.0,4,AS8,Z,10.1,7.8,9.1,31,213,5.0,4.0
21212,2025,Volvo,XC60 B5 AWD,Sport utility vehicle: Small,2.0,4,AS8,Z,10.0,7.8,9.0,31,212,5.0,6.0
21213,2025,Volvo,XC90 B6 AWD,Sport utility vehicle: Standard,2.0,4,AS8,Z,11.5,9.0,10.4,27,244,5.0,6.0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21214 entries, 0 to 21213
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Model year            21214 non-null  int64
 1   Make                  21214 non-null  object
 2   Model                 21214 non-null  object
 3   Vehicle class         21214 non-null  object
 4   Engine size (L)       21214 non-null  float64
 5   Cylinders             21214 non-null  int64
 6   Transmission          21214 non-null  object
 7   Fuel type             21214 non-null  object
 8   City (L/100 km)       21214 non-null  float64
 9   Highway (L/100 km)    21214 non-null  float64
 10  Combined (L/100 km)   21214 non-null  float64
 11  Combined (mpg)        21214 non-null  int64
 12  CO2 emissions (g/km)  21214 non-null  int64
 13  CO2 rating            9525 non-null   float64
 14  Smog rating           8419 non-null   float64
dtypes: float64(6), int64(4), object(5)
memory usage: 2.4+ MB

In [13]:
df.query('Make == "Audi" and Model.str.contains("Coup")') # acento pode ter causado o erro de encoding nos dois últimos arquivos

,Model year,Make,Model,Vehicle class,Engine size (L),Cylinders,Transmission,Fuel type,City (L/100 km),Highway (L/100 km),Combined (L/100 km),Combined (mpg),CO2 emissions (g/km),CO2 rating,Smog rating
42,2005,Audi,TT Coupe,Minicompact,1.8,4,AS6,Z,12.8,8.9,11.0,26,253,NaN,NaN
43,2005,Audi,TT Coupe quattro,Minicompact,1.8,4,M6,Z,13.2,9.0,11.3,25,260,NaN,NaN
44,2005,Audi,TT Coupe quattro,Minicompact,3.2,6,AS6,Z,12.0,9.6,10.9,26,251,NaN,NaN
1053,2006,Audi,TT Coupe quattro,Minicompact,1.8,4,M6,Z,13.2,9.0,11.3,25,260,NaN,NaN
1054,2006,Audi,TT Coupe quattro,Minicompact,3.2,6,AS6,Z,13.8,9.8,12.0,24,276,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19791,2024,Audi,RS 5 Coupé,Subcompact,2.9,6,AS8,Z,12.9,9.3,11.3,25,264,4.0,5.0
19799,2024,Audi,S5 Coupé quattro,Subcompact,3.0,6,AS8,Z,11.1,8.1,9.7,29,228,5.0,5.0
20542,2025,Audi,A5 Coupé 45 TFSI quattro,Subcompact,2.0,4,AM7,Z,10.1,7.3,8.8,32,207,5.0,4.0
20560,2025,Audi,RS 5 Coupé,Subcompact,2.9,6,AS8,Z,12.9,9.3,11.3,25,264,4.0,4.0
20568,2025,Audi,S5 Coupé quattro,Subcompact,3.0,6,AS8,Z,11.0,8.1,9.7,29,228,5.0,4.0

In [14]:
import re 

def string_to_snake_case(string):
    string = re.sub('/', ' ', string)                      # Substitui "/" por espaço
    string = re.sub(' +', ' ', string)                     # Substitui múltiplos espaços por um espaço
    string = re.sub(' ', '_', string)                      # Substitui espaço por _
    string = re.sub('([a-z0-9])([A-Z])', r'\1_\2', string) # Adiciona _ entre letras minúsculas e maiúsculas
    string = re.sub(r'\(', '', string)                     # elimina parênteses iniciais
    string = re.sub(r'\)', '', string)                     # elimina parênteses finais
    
    return string.lower()

In [15]:
df.columns = [string_to_snake_case(coluna) for coluna in df.columns]

df.head()

,model_year,make,model,vehicle_class,engine_size_l,cylinders,transmission,fuel_type,city_l_100_km,highway_l_100_km,combined_l_100_km,combined_mpg,co2_emissions_g_km,co2_rating,smog_rating
0,2005,Acura,1.7EL,Compact,1.7,4,A4,X,9.2,7.2,8.3,34,191,NaN,NaN
1,2005,Acura,1.7EL,Compact,1.7,4,M5,X,9.1,7.3,8.3,34,191,NaN,NaN
2,2005,Acura,MDX AWD,Sport utility vehicle,3.5,6,A5,Z,15.9,11.1,13.7,21,315,NaN,NaN
3,2005,Acura,NSX,Two-seater,3.0,6,AS4,Z,15.1,10.5,13.0,22,299,NaN,NaN
4,2005,Acura,NSX,Two-seater,3.2,6,M6,Z,15.1,10.5,13.0,22,299,NaN,NaN

In [16]:
df.to_parquet(DADOS_CONSOLIDADOS, index=False)